export type PostStatus = "draft" | "scheduled" | "published";

export interface PostAuthor {
  /** Stable Cognito subject captured from the authenticated access token. */
  id: string;
  /** Editorial snapshot kept with the post even if the display name changes later. */
  name: string;
}

export type CoverImageStatus = "processing" | "ready" | "failed";
export type ImageFormat = "avif" | "webp";

export interface ImageVariant {
  format: ImageFormat;
  width: number;
  height: number;
  url: string;
}

export interface CoverImage {
  id: string;
  status: CoverImageStatus;
  width: number | null;
  height: number | null;
  aspectRatio: number | null;
  variants: ImageVariant[];
  /** Largest WebP variant, used by img, Open Graph and JSON-LD. */
  fallbackUrl?: string;
  error?: string;
}

export interface Post {
  slug: string;
  title: string;
  description: string;
  category: string;
  tags: string[];
  author: PostAuthor;
  /** Responsive cover generated by the image-processing pipeline. */
  coverImage: CoverImage | null;
  contentMarkdown: string;
  status: PostStatus;
  /** ISO 8601 in UTC. Required when status is "scheduled" or "published". */
  publishAt: string | null;
  createdAt: string;
  updatedAt: string;
  viewCount: number;
  sideEffects: {
    status: "pending" | "ready" | "failed";
    updatedAt: string;
    error?: string;
  };
}

/** Fields the admin can set when creating/editing a post. Server fills the rest. */
export type PostInput = Pick<
  Post,
  "slug" | "title" | "description" | "category" | "tags" | "coverImage" | "contentMarkdown" | "status" | "publishAt"
>;

/** Update contract used for optimistic concurrency. */
export type PostUpdateInput = PostInput & { expectedUpdatedAt: string };

export interface MetricsPeriod {
  /** Window length in days: 7, 30 or 90. */
  days: number;
  /** Sum of qualified views in the last `days` days, including today. */
  qualifiedViews: number;
  /** Sum of qualified views in the equally-long window immediately before this one. */
  previousQualifiedViews: number;
  /** (qualifiedViews - previousQualifiedViews) / previousQualifiedViews, or null when previousQualifiedViews is 0. */
  changeRatio: number | null;
  topPosts: Array<{ slug: string; title: string; qualifiedViews: number }>;
}

export interface MetricsSummary {
  totalViews: number;
  totalPosts: number;
  postsByViews: Array<{ slug: string; title: string; viewCount: number }>;
  /** Daily aggregates only exist from the day this feature shipped onward — older days are absent, not zero. */
  periods: MetricsPeriod[];
}

export type AdminPostListStatus = PostStatus;

export type AdminPostSummary = Pick<
  Post,
  "slug" | "title" | "status" | "category" | "publishAt" | "updatedAt"
>;

export interface AdminPostList {
  items: AdminPostSummary[];
  count: number;
  year?: number;
}

export interface PresignedUpload {
  uploadUrl: string;
  fields: Record<string, string>;
  image: CoverImage;
}
