server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;
  client_max_body_size 8m;

  location /api/ {
    proxy_pass http://api:3000;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location /images/ {
    proxy_pass http://api:3000;
    proxy_set_header Host $host;
  }

  location /admin/ {
    try_files $uri $uri/ /admin/index.html;
  }

  location / {
    try_files $uri $uri/ $uri/index.html /404.html;
  }
}
